apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-app
spec:
  selector:
    matchLabels:
      app: product-service-app
  template:
    metadata:
      labels:
        app: product-service-app
    spec:
      containers:
      - name: product-service-app
        image: calebliu2014/product-service
        ports:
        - containerPort: 8001
        env:
          - name: EUREKA_SERVER
            valueFrom:
              configMapKeyRef:
                key: eureka_server
                name: eureka-cm
          - name: CONFIG_SERVER
            valueFrom:
              configMapKeyRef:
                key: config_server
                name: config-cm
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: db_host
                name: mysql-cm

---

apiVersion: v1
kind: Service
metadata:
  name: product-service-svc
spec:
  selector:
    app: product-service-app
  ports:
  - port: 80
    targetPort: 8001
        
