version: '3'
services:
  serviceregistry:
    image: 'serviceregistryi'
    container_name: serviceregistryc
    ports:
      - '8050:8050'
  configservice:
    image: 'configservicei'
    container_name: configservicec
    ports:
      - '8051:8051'
    environment:
      - SERVER_URL=host.docker.internal
    depends_on:
      - serviceregistry
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://configservice:8051/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
  apigateway:
    image: 'apigatewayi'
    container_name: apigatewayc
    ports:
      - '8052:8052'
    environment:
      - SERVER_URL=host.docker.internal
    depends_on:
      configservice:
        condition: service_healthy
  orderservice:
    image: 'orderservicei'
    container_name: orderservicec
    ports:
      - '8002:8002'
    environment:
      - SERVER_URL=host.docker.internal
      - DB_HOST=host.docker.internal
    depends_on:
      configservice:
        condition: service_healthy
  productservice:
    image: 'productservicei'
    container_name: productservicec
    ports:
      - '8001:8001'
    environment:
      - SERVER_URL=host.docker.internal
      - DB_HOST=host.docker.internal
    depends_on:
      configservice:
        condition: service_healthy
  paymentservice:
    image: 'paymentservicei'
    container_name: paymentservicec
    ports:
      - '8003:8003'
    environment:
      - SERVER_URL=host.docker.internal
      - DB_HOST=host.docker.internal
    depends_on:
      configservice:
        condition: service_healthy
